// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeK99hLki3UlHSxLcIuDZYhMIBbmrRPVA',
    appId: '1:664919462493:android:c05ec79061b1c2e31333b4',
    messagingSenderId: '664919462493',
    projectId: 'ascendant-acre-382709',
    storageBucket: 'ascendant-acre-382709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAibtq8fZDnKd0mMot6M0s-2WILLxopag',
    appId: '1:664919462493:ios:d42c898423c9a8981333b4',
    messagingSenderId: '664919462493',
    projectId: 'ascendant-acre-382709',
    storageBucket: 'ascendant-acre-382709.appspot.com',
    androidClientId: '664919462493-stngcud8om0dsmqnv4p7ki3ltpg1t1vh.apps.googleusercontent.com',
    iosClientId: '664919462493-fq8oohjn26oh9uar04qrct6assgmuhot.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveapp',
  );
}
